import {
  Wifi,
  UtensilsCrossed,
  ParkingCircle,
  Snowflake,
  Flame,
  WashingMachine,
  Tv,
  Laptop,
  PawPrint,
  Waves,
  Dumbbell,
  Coffee,
  Zap,
  CheckCircle,
  Droplets,
  Wind,
  Shirt,
  BedDouble,
  Microwave,
  Refrigerator,
  CookingPot,
  Utensils,
  Table2,
  Sun,
  TreePine,
  Armchair,
  ArrowUpDown,
  Mountain,
  KeyRound,
  CalendarDays,
  Luggage,
  BellRing,
  BriefcaseMedical,
  FireExtinguisher,
  Camera,
  Lock,
  DoorOpen,
  Bath,
  MapPin,
  Car,
  Award,
  LucideIcon,
} from "lucide-react";

/** Icon keys come from the amenity catalogue in the backend seed and from
 *  listing highlights; anything unknown falls back to a tick. */
const ICON_MAP: Record<string, LucideIcon> = {
  wifi: Wifi,
  kitchen: UtensilsCrossed,
  parking: ParkingCircle,
  ac: Snowflake,
  heating: Flame,
  washer: WashingMachine,
  dryer: WashingMachine,
  tv: Tv,
  workspace: Laptop,
  laptop: Laptop,
  pets: PawPrint,
  "hot-tub": Bath,
  bath: Bath,
  pool: Waves,
  waves: Waves,
  gym: Dumbbell,
  breakfast: Coffee,
  coffee: Coffee,
  fireplace: Flame,
  flame: Flame,
  "ev-charger": Zap,
  zap: Zap,
  droplet: Droplets,
  wind: Wind,
  iron: Shirt,
  hanger: Shirt,
  bed: BedDouble,
  microwave: Microwave,
  fridge: Refrigerator,
  cooking: CookingPot,
  utensils: Utensils,
  table: Table2,
  sun: Sun,
  tree: TreePine,
  armchair: Armchair,
  elevator: ArrowUpDown,
  mountain: Mountain,
  key: KeyRound,
  calendar: CalendarDays,
  luggage: Luggage,
  alarm: BellRing,
  "first-aid": BriefcaseMedical,
  extinguisher: FireExtinguisher,
  camera: Camera,
  lock: Lock,
  door: DoorOpen,
  "door-open": DoorOpen,
  "map-pin": MapPin,
  car: Car,
  award: Award,
};

export default function AmenityIcon({ icon, size = 22, className = "" }: { icon: string; size?: number; className?: string }) {
  const Icon = ICON_MAP[icon] || CheckCircle;
  return <Icon size={size} className={className} strokeWidth={1.5} />;
}
